- name: build vm with Packer
  command: "packer build -var-file {{ item.packer_varfile }} {{ item.packer_template }}"
  args:
    chdir: "/data/templates"
  become: false

- name: get qcow name
  find:
    path: "/data/templates/output-qemu"
  register: qemu_output

- name: move qcow into libvirt pool
  command: "mv {{ qemu_output.files[0].path }} /data/vms"

- name: remove output-qemu
  file:
    path: /data/templates/output-qemu
    state: absent

# we don't need to keep the cache for another build
# and we need to be savy on disk space here
- name: remove packer cache
  file:
    path: /data/templates/packer_cache
    state: absent

- name: set qcow filename
  set_fact:
    vms_image_filename: "{{ qemu_output.files[0].path | basename }}"
