---
- name: update cache
  apt:
    update_cache: yes

- name: install build dependencies
  package:
    name: "{{ item }}"
  with_items:
    - bc
    - fakeroot
    - dpkg-dev
    - flex
    - bison
    - libelf-dev
    - libssl-dev

- name: configure kernel using distro's config
  command: make olddefconfig
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: configure KVM introspection
  command: "./scripts/config {{ item.switch }} {{ item.option }}"
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false
  with_items:
    # disable trusted keys debian/certs/debian-uefi-certs.pem
    # as they are only available in the kernel sources, and we don't
    # care about SecureBoot
    - { switch: "--disable", option: "SYSTEM_TRUSTED_KEYS" }
    - { switch: "--disable", option: "MODULE_SIG_KEY" }
    # ensure KVM is enabled
    - { switch: "--enable", option: "KVM" }
    - { switch: "--enable", option: "KVM_INTEL" }
    - { switch: "--enable", option: "KVM_AMD" }
    # enable KVM_INTROSPECTION
    - { switch: "--enable", option: "KVM_INTROSPECTION" }
    # enable REMOTE_MAPPING
    # -> !TRANSPARENT_HUGEPAGE
    - { switch: "--disable", option: "TRANSPARENT_HUGEPAGE" }
    - { switch: "--enable", option: "REMOTE_MAPPING" }

- name: append -kvmi to kernel version string
  lineinfile:
    dest: "{{ root_dir }}/kvm/Makefile"
    regexp: '^EXTRAVERSION ='
    line: 'EXTRAVERSION = -kvmi'
  become: false

- name: set default config to new options
  command: make olddefconfig
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: install kvm
  include: install_deb.yml
  when: kvm_install_package

- name: install kvm
  include: install_normal.yml
  when: not kvm_install_package

- name: set kvmi kernel as default
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_DEFAULT'
    line: 'GRUB_DEFAULT="1>0"'

- name: update GRUB configuration
  command: update-grub

- name: setup libkvmi
  include: libkvmi.yml
